blog/urls.py
from django.conf.urls import url, include
from . import views


article_patterns = [
    url('create', views.ArticleCreateView.as_view(), name='create'),
    url(r'(?P<username>[a-zA-Z0-9_-]{1,20})/(?P<feedslug>[a-zA-Z0-9_-]{1,100})/(?P<slug>[a-zA-Z0-9_-]{1,100})/edit$',
        views.ArticleEditView.as_view(),
        name='edit'),
    url(r'(?P<username>[a-zA-Z0-9_-]{1,20})/(?P<feedslug>[a-zA-Z0-9_-]{1,100})/(?P<slug>[a-zA-Z0-9_-]{1,100})$', 
        views.ArticleDetailView.as_view(), 
        name='permalink'),
]

# question_patterns = [
#     url('create', views.CreateQuestionView.as_view(), name='create')
# ]


# url_patterns = [
#     url('create', views.CreateUrlView.as_view(), name='create')
# ]

urlpatterns = [
    # permalink for post
    # p/username/feedslug/postslug
    # url(r'p/(?P<username>[a-zA-Z0-9_-]{1,20})/(?P<feedslug>[a-zA-Z0-9_-]{1,50})/(?P<slug>[a-zA-Z0-9_-]{1,80})$', 
    #     views.ViewFeedItem.as_view(),
    #     name='permalink'),
        
    url('^article/', include(article_patterns, namespace='article')),
    # url('^question/', include(question_patterns, namespace='question')),
    # url('^url/', include(url_patterns, namespace='url'))
]

feed/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    # logged in users drafts
    url(r'drafts$', views.DraftsFeed.as_view(), name='drafts'),
    
    # list of user's feeds, also form to create feed if logged in user = username
    # f/user/feeds
    url(r'(?P<username>[a-zA-Z0-9_-]{1,20})/feeds$', 
        views.CreateFeedView.as_view(), 
        name='user-feed-list'),

    # a feed belonging to a specific user
    # f/user/myfeed
    url(r'(?P<username>[a-zA-Z0-9_-]{1,20})/(?P<feedslug>[a-zA-Z0-9_-]{1,100})$', 
        views.UserCreatedFeed.as_view(), 
        name='user-feed'),


    # view a user's feeds
    # f/user
    url(r'(?P<username>[a-zA-Z0-9_-]{1,20})$',
        views.UserFeed.as_view(),
        name='user'),

    # main feed
    url(r'^$', views.OverviewFeed.as_view(), name='overview')
]

hackshaw/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.defaults import page_not_found
from user.views import LoginView, LogoutView, RegisterView, AuthorRequestView
from core.views import RedirectView
from feed.views import OverviewFeed

urlpatterns = [
    # authentication urls
    url(r'^login$', LoginView.as_view(), name='login'),
    url(r'^register$', RegisterView.as_view(), name='register'),
    url(r'^author_request$', AuthorRequestView.as_view(), name='author-request'),
    url(r'^logout$', LogoutView.as_view(), name='logout'),

    # home page is the overview feed
    url(r'^$', OverviewFeed.as_view(), name='homepage'),

    # user profile urls
    url(r'^u/', include('user.urls', namespace='user')),

    # feed urls
    url(r'^f/', include('feed.urls', namespace='feed')),

    # article/ question/ survey/ etc.
    url(r'^', include('blog.urls', namespace='blog')),

    # admin urls
    url(r'^admin/login', RedirectView.as_view(), {'url': 'login'}),
    url(r'^admin/', admin.site.urls)

]

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from gm2m import GM2MField
from django.dispatch import receiver
from django.template.defaultfilters import slugify
from django.utils import timezone
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from .markdown_extensions import SPEmbedExtension, SPClassesExtension
import markdown
import bleach


# Markdown parameters for users without the blog.embed_content permission
extensions = ['markdown.extensions.fenced_code',
              'markdown.extensions.codehilite',
              'markdown.extensions.nl2br',
              'markdown.extensions.tables',
              SPClassesExtension()]
allowed_tags = set(['h1', 'h2', 'h3', 'h4', 'b', 'em', 
                    'ul', 'ol', 'li', 'code', 'blockquote',
                    'p', 'strong', 'pre', 'table', 'tr', 'td', 
                    'th', 'tbody', 'thead', 'div', 'span', 'br', 'a'])
allowed_attributes = ['class']

# extra markdown parameters for users WITH the blog.embed_content permission
# potentially unsafe, but I think probably not
embed_allowed_tags = allowed_tags.copy()
embed_allowed_tags.update(['script', 'iframe'])
embed_allowed_attributes = allowed_attributes + ['href', 'src', 'allow', 'allowfullscreen', 
                                                 'frameborder', 'height', 'gesture']
embed_extensions = extensions + [SPEmbedExtension()]


def markdown_to_html(md, with_embeds=False):
    if with_embeds:
        html = bleach.clean(markdown.markdown(md, extensions=embed_extensions),
                                              tags=embed_allowed_tags,
                                              attributes=embed_allowed_attributes)
    else:
        html = bleach.clean(markdown.markdown(md, extensions=extensions),
                                              tags=allowed_tags,
                                              attributes=allowed_attributes)
    return bleach.linkify(html)


class FeedItem(models.Model):
    """ Abstract model containing fields common to all types of feed entries """
    published_choices = ((False, 'Draft'), (True, 'Publish'))
    
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    # fields defining this entry: these are common to all types of entries
    # content_object contains specific entry with specific fields
    slug = models.SlugField(max_length=80)
    headline = models.CharField(max_length=80)
    published = models.BooleanField(default=False, choices=published_choices)
    tags = GM2MField('core.Tag')
    
    # required fields for the generic relationship
    # content_object is the instance of FeedItemBase
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    feed = GenericForeignKey('content_type', 'object_id')

    class Meta:
        ordering = ('-created',)
        default_related_name = '%(model_name)s'
        unique_together = ['object_id', 'slug']
        permissions = (
            ('create_feed_item', 'create a feed item or one of its subclasses'),
            ('embed_content', 'embed content into a feeditem - security purposes')
        )

    @property
    def short_entry_template(self):
        return self.child_object.short_entry_template

    @property
    def child_object(self):
        for f in self._meta.related_objects:
            if isinstance(f, models.OneToOneRel) and hasattr(self, f.related_model.__name__.lower()):
                return getattr(self, f.related_model.__name__.lower())

    def save(self, *args, **kwargs):
        self.slug = slugify(self.headline)
        return super(FeedItem, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return self.child_object.get_absolute_url()

    def __repr__(self):
        return '<FeedItemBase type=%r headline=%r>' % (self.__class__.__name__, self.headline)


class Article(FeedItem):
    markdown = models.TextField()
    html = models.TextField()
    summary = models.CharField(max_length=300)
    short_entry_template = 'article/article.html'

    def save(self, *args, **kwargs):
        self.html = markdown_to_html(self.markdown,
                                     with_embeds=self.feed.user.has_perm('blog.embed_content'))
        self.summary = bleach.clean(self.html, tags=[], strip=True)[:299]
        return super(Article, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:article:permalink', kwargs={'username': self.feed.user.username,
                                                         'feedslug': self.feed.slug,
                                                         'slug': self.slug})
    
    @property
    def permalink(self):
        return self.get_absolute_url()

    def __repr__(self):
        return '<Article %r>' % self.headline

blog/forms.py
from django.forms import ModelForm, ModelChoiceField, Textarea, CharField, Select, ChoiceField
from django.urls import reverse
from .models import Article
from core.models import Tag
from feed.models import Feed
from django.contrib.auth import get_user, get_user_model
from django.contrib.contenttypes.models import ContentType
import re

TAG_RE = re.compile(r'[a-zA-Z0-9-!+]{,20}')
def valid_tag(tag):
    return bool(re.match(TAG_RE, tag))


class ItemAdminBaseForm(ModelForm):
    feed = ModelChoiceField(queryset=Feed.objects.all())
    tag = CharField(max_length=255, required=False)

    class Meta:
        fields = ['feed', 'published', 'headline', 'tag']
        widgets = {}

    def clean_tag(self):
        data = self.cleaned_data.get('tag', '')
        ret = [Tag.objects.get_or_create(name=t)[0] for t in data.split(' ')[:10]
                                                    if valid_tag(t)]
        return ret

    def save(self, *args, **kwargs):
        f = self.cleaned_data['feed']
        self.instance.content_type = ContentType.objects.get_for_model(f)
        self.instance.object_id = f.id
        instance = super(ItemAdminBaseForm, self).save(*args, **kwargs)
        instance.tags = self.cleaned_data['tag']
        return instance
    

class ItemBaseForm(ItemAdminBaseForm):
    # add fields required for the associated FeedEntry
    feed = ModelChoiceField(queryset=Feed.objects.none())

    def __init__(self, *args, **kwargs):
        # # pull out extra kwargs
        current_user = kwargs.pop('current_user', None)
        if current_user is None:
            raise ValueError('Must specify either current_user or feed_queryset when initializing a BlogItemForm')

        #  init super with remaining args
        super(ItemBaseForm, self).__init__(*args, **kwargs)
        self.fields['feed'].queryset = Feed.objects.filter(user=current_user)


class ArticleForm(ItemBaseForm):
    class Meta(ItemBaseForm.Meta):
        model = Article
        fields = ItemBaseForm.Meta.fields + ['markdown']
        widgets = {**ItemBaseForm.Meta.widgets, **{'markdown': Textarea()}}


class ArticleAdminForm(ItemAdminBaseForm):
    class Meta(ArticleForm.Meta):
        pass

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, FormView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic import DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth import get_user_model
from django.core.exceptions import PermissionDenied
from .forms import ArticleForm
from .models import Article, FeedItem

User = get_user_model()


class DetailItemBase(DetailView):
    def get_queryset(self):
        return FeedItem.objects.filter(feeds__user__username=self.kwargs['username'],
                                       feeds__slug=self.kwargs['feedslug'])


class CreateItemBase(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    success_url = '/'
    template_name = 'items/feed_item_form.html'
    permission_required = 'blog.create_feed_item'
    login_url = reverse_lazy('author-request')

    def get_form_kwargs(self):
        kwargs = super(CreateItemBase, self).get_form_kwargs()
        kwargs['current_user'] = self.request.user
        return kwargs

    def handle_no_permission(self):
        print('handling no permission')
        return super(CreateItemBase, self).handle_no_permission()


class EditItemBase(LoginRequiredMixin, UpdateView):
    template_name = 'items/feed_item_form.html'
    
    def get_form_kwargs(self):
        kwargs = super(EditItemBase, self).get_form_kwargs()
        kwargs['current_user'] = self.request.user
        return kwargs

    def get_initial(self):
        initial = super(EditItemBase, self).get_initial()
        initial['tag'] = " ".join([t.name for t in self.object.tags.all()])
        initial['feed'] = self.object.feed.id
        return initial

    def get_queryset(self):
        if self.request.user.username != self.kwargs['username']:
            raise PermissionDenied
        return FeedItem.objects.filter(feeds__user__username=self.kwargs['username'],
                                       feeds__slug=self.kwargs['feedslug'])


class ArticleCreateView(CreateItemBase):
    form_class = ArticleForm


class ArticleEditView(EditItemBase):
    form_class = ArticleForm
    model = Article

    def get_object(self, *args, **kwargs):
        feeditem = super(ArticleEditView, self).get_object(*args, **kwargs)
        return getattr(feeditem, 'article', None)

    def get_initial(self):
        initial = super(ArticleEditView, self).get_initial()
        initial['markdown'] = self.object.article.markdown
        return initial


class ArticleDetailView(DetailItemBase):
    template_name = 'article/article_detail.html'


class QuestionDetailView(DetailItemBase):
    model = Article
    template_name = 'question/question_detail.html'


class QuestionCreateView(LoginRequiredMixin, CreateView):
    model = Article
    template_name = 'question/question_form.html'



                                

blog/templates/article/article.html
{% load blog_custom_tags %}
{% load navigation_tags %}

<div class="row">
    <div class="">
        <div class="card article-summary-card hoverable">
            <div class="card-content">
                <h2 class="card-title"><a href="{{ entry.article.permalink }}">{{ entry.headline }}</a></h2>
                <div class="row">
                    <div class="valign-wrapper">
                        <div class="col s1 pr-0 right-align hide-on-med-and-down">
                            <img class="circle" src="{% user_gravatar_url entry.feed.user 30 %}">
                        </div>
                        <div class="col m12 l11">
                            <p class="row article-meta">
                                <span class="left">
                                    {{ entry.created|timesince }} ago<br />
                                    by <a href="{% url 'feed:user' username=entry.feed.user.username %}">{{ entry.feed.user.username }}</a>
                                    in <a href="{% url 'feed:user-feed' username=entry.feed.user.username feedslug=entry.feed.slug %}">{{ entry.feed.name }}</a> 
                                </span>
                                {% if not entry.published %}
                                <span class="right">
                                    <a class="btn disabled btn-small">draft</a>
                                </span>
                                {% endif %}
                            </p>
                        </div>
                    </div>
                </div>

                <p class="row">
                    {{ entry.article.summary }}
                </p>
                <p class="row section">
                    {% for tag in entry.tags.all %}
                    <a class="left chip btn-small" data-badge-caption="">{{ tag.name }}</a>
                    {% endfor %}
                </p>
                <p class="row section">
                    <span class="valign-center">
                        <i class="material-icons">star_border</i><span>&nbsp;{% article_lightbulb_count entry %}&nbsp;&nbsp;</span>
                        <i class="material-icons">comment</i><span>&nbsp;{% article_lightbulb_count entry %}</span>
                    </span>
                </p>
            </div>
        </div>
    </div>
</div>

blog/templates/article/article_detail.html
{% extends "core/containers/materialize_base.html" %}
{% load blog_custom_tags %}
{% load static %}

{% block css %}
{{ block.super }}
<link href="{% static "core/css/hilite.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="post-header">
    <div class="container">
        <div class="row mb-0 pt-24">
            <h5 class="mb-0">{{ object.headline }}</h4>
        </div>
        <div class="row valign-wrapper">
            <div class="col s1 center-align hide-on-med-and-down">
                <img class="circle" src="{% user_gravatar_url object.feed.user 35 %}">
            </div>
            <div class="col l11">
                <p class="row article-meta">
                    <span class="left">
                        {{ object.created|timesince }} ago<br />
                        By <a href="{% url 'feed:user' username=object.feed.user.username %}">
                            {{ object.feed.user.username }}
                        </a>
                        in <a href="{% url 'feed:user-feed' username=object.feed.user.username feedslug=object.feed.slug %}">
                            {{ object.feed.name }}
                        </a> 
                    </span>
                    <span class="right">
                        {% if not object.published %}
                            <a class="btn disabled btn-small">draft</a>
                        {% endif %}
                        {% if request.user == object.feed.user %}
                        <a href="{% url 'blog:article:edit' username=object.feed.user.username feedslug=object.feed.slug slug=object.slug %}"
                           class="btn btn-small">Edit</a>
                        {% endif %}
                    </span>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="divider"></div>
<div class="container">
    <div class="row">
        <div class="col s12 m10 l8 offset-m1 offset-l2">
            
            {{ object.article.html|safe }}

            <div class="row section mt-0">
                {% for tag in object.tags.all %}
                <a class="left chip btn-small" data-badge-caption="">{{ tag.name }}</a>
                {% endfor %}
            </div>

        </div>
    </div>
</div>
<div class="divider"></div>

<!-- disqus -->
{% endblock content %}