blog/urls.py
from django.conf.urls import url, include
from . import views


article_patterns = [
    url('create', views.ArticleCreateView.as_view(), name='create'),
    url(r'(?P<username>[a-zA-Z0-9_-]{1,20})/(?P<feedslug>[a-zA-Z0-9_-]{1,100})/(?P<slug>[a-zA-Z0-9_-]{1,100})/edit$',
        views.ArticleEditView.as_view(),
        name='edit'),
    url(r'(?P<username>[a-zA-Z0-9_-]{1,20})/(?P<feedslug>[a-zA-Z0-9_-]{1,100})/(?P<slug>[a-zA-Z0-9_-]{1,100})$', 
        views.ArticleDetailView.as_view(), 
        name='permalink'),
]

# question_patterns = [
#     url('create', views.CreateQuestionView.as_view(), name='create')
# ]


# url_patterns = [
#     url('create', views.CreateUrlView.as_view(), name='create')
# ]

urlpatterns = [
    # permalink for post
    # p/username/feedslug/postslug
    # url(r'p/(?P<username>[a-zA-Z0-9_-]{1,20})/(?P<feedslug>[a-zA-Z0-9_-]{1,50})/(?P<slug>[a-zA-Z0-9_-]{1,80})$', 
    #     views.ViewFeedItem.as_view(),
    #     name='permalink'),
        
    url('^article/', include(article_patterns, namespace='article')),
    # url('^question/', include(question_patterns, namespace='question')),
    # url('^url/', include(url_patterns, namespace='url'))
]

hackshaw/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.defaults import page_not_found
from user.views import LoginView, LogoutView, RegisterView, AuthorRequestView
from core.views import RedirectView
from feed.views import OverviewFeed

urlpatterns = [
    # authentication urls
    url(r'^login$', LoginView.as_view(), name='login'),
    url(r'^register$', RegisterView.as_view(), name='register'),
    url(r'^author_request$', AuthorRequestView.as_view(), name='author-request'),
    url(r'^logout$', LogoutView.as_view(), name='logout'),

    # home page is the overview feed
    url(r'^$', OverviewFeed.as_view(), name='homepage'),

    # user profile urls
    url(r'^u/', include('user.urls', namespace='user')),

    # feed urls
    url(r'^f/', include('feed.urls', namespace='feed')),

    # article/ question/ survey/ etc.
    url(r'^', include('blog.urls', namespace='blog')),

    # admin urls
    url(r'^admin/login', RedirectView.as_view(), {'url': 'login'}),
    url(r'^admin/', admin.site.urls)

]

user/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'notifications$', views.NotificationsView.as_view(), name='notifications'),
    url(r'notifications/delete/(?P<pk>[0-9]+)$',
        views.DeleteNotificationView.as_view(), name='delete-notification'),
    url(r'(?P<username>[a-zA-Z0-9]{1,50})/profile$', views.ProfileView.as_view(), name='profile'),
    url(r'(?P<username>[a-zA-Z0-9]{1,50})/profile/edit', views.ProfileEditView.as_view(), name='profile-edit')
]

user/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin, Group
from django.contrib.auth.validators import ASCIIUsernameValidator
import hashlib
from blog.models import FeedItem



class CustomUserManager(BaseUserManager):
    def create_user(self, username, email, password):
        user = self.init_user(username, email, password)
        user.save()
        return user
    
    def create_superuser(self, username, email, password):
        user = self.init_user(username, email, password)
        user.is_admin = True
        user.save()
        return user
        
    def init_user(self, username, email, password):
        user = self.model(username=username,
                          email=email)
        user.set_password(password)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(verbose_name='Email Address',
                              max_length=255,
                              unique=True)
    username = models.CharField(max_length=20, 
                                validators=[ASCIIUsernameValidator],
                                unique=True)
    icon_hash = models.CharField(max_length=150)
    about_me = models.CharField(max_length=150, blank=True)
    github_link = models.URLField(verbose_name='github', blank=True)
    linkedin_link = models.URLField(verbose_name='linkedin', blank=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = CustomUserManager()
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'password']

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.username

    def save(self, *args, **kwargs):
        identifier = self.email if self.email else self.username
        self.icon_hash = hashlib.md5(identifier.encode()).hexdigest()
        super(User, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('user:profile', kwargs={'username': self.username})

    def get_gravatar_url(self, size=150): 
        return 'https://www.gravatar.com/avatar/{}?s={}&d=identicon'.format(self.icon_hash,
                                                                            size)

    def notify(self, message):
        Notification.objects.create(user=self, text=message)

    def clear_notifications(self):
        return self.notifications.all().delete()

    def get_top_posts(self, count=3):
        return FeedItem.objects.filter(feeds__user=self).all()[:count]

    @property
    def gravatar_url(self):
        return self.get_gravatar_url()

    @property
    def profile_url(self):
        return reverse('user:profile', kwargs={'username': self.username})

    @property
    def is_staff(self):
        return self.is_admin

    @property
    def is_superuser(self):
        return self.is_admin

    class Meta:
        default_related_name = 'users'

    def __repr__(self):
        return '<User %r>' % self.username


class Notification(models.Model):
    created = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notifications')
    text = models.CharField(max_length=255)
    link = models.URLField(blank=True, null=True)

    class Meta:
        ordering = ('-created',)


class RegistrationRequest(models.Model):
    created = models.DateTimeField(auto_now=True)
    about = models.TextField(verbose_name='About you',
                             max_length=5000,
                             help_text='Please describe a little bit about yourself and/or what you will write about. This is just to prevent spam, I am sure we will be happy to have you!')
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ('-created',)

user/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm, Textarea
from .models import User


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('email',)


class ProfileEditForm(ModelForm):
    class Meta:
        model = User
        fields = ['email', 'github_link', 'linkedin_link', 'about_me']
        widgets = {'about_me': Textarea()}


class AdminForm(ModelForm):
    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields + \
                 ('email', 'about_me', 'is_active', 'is_admin', 'groups')

user/views.py
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect, JsonResponse
from django.views.generic import DetailView, View, ListView
from django.views.generic.edit import UpdateView, CreateView, FormView
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from .forms import RegisterForm, ProfileEditForm
from .models import RegistrationRequest, Notification   
from feed.models import Feed
from core.models import Tag


class RegisterView(FormView):
    template_name = "registration/register.html"
    form_class = RegisterForm
    success_url = reverse_lazy('feed:overview')

    def form_valid(self, form):
        new_user = super(RegisterView, self).form_valid(form)
        new_user.notify('Welcome to SemperPy! Have a look around. Feedback is always appreciated.')
        return new_user


class AuthorRequestView(LoginRequiredMixin, CreateView):
    model = RegistrationRequest
    fields = ['about']
    template_name = 'registration/author_request.html'
    success_url = reverse_lazy('feed:overview')

    def form_valid(self, form):
        req = form.instance.user = self.request.user
        self.request.user.notify('Your authorship request has been recieved, check back later!')
        return super(AuthorRequestView, self).form_valid(form)

    def get(self, request, *args, **kwargs):
        if RegistrationRequest.objects.filter(user=request.user).exists():
            return HttpResponseRedirect('/')
        return super(AuthorRequestView, self).get(request, *args, **kwargs)


class LoginView(LoginView):
    pass


class LogoutView(LogoutView):
    pass


class ProfileView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    slug_field = 'username'
    slug_url_kwarg = 'username'
    context_object_name = 'profile_of'


class ProfileEditView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileEditForm
    slug_field = 'username'
    slug_url_kwarg = 'username'
    template_name_suffix = '_edit'


class NotificationsView(LoginRequiredMixin, ListView):
    model = Notification
    paginate_by = 20
    paginate_orphans = 5
    template_name = 'user/user_notifications.html'

    def get_queryset(self):
        return self.request.user.notifications.all()


class DeleteNotificationView(LoginRequiredMixin, View):
    def get(self, request, pk):
        delete = Notification.objects.filter(user=self.request.user,
                                             pk=pk).delete()
        status = 'deleted' if delete[0] > 0 else 'not_deleted'
        return JsonResponse({'status': status})

user/templates/user/notifications.html
<ul class="collection">
    {% for notification in object_list %}
    <li id="notification_{{ notification.id }}" class="collection-item avatar">
        <i class="material-icons circle">folder</i>
        <h5 class="title mr-10">{{ notification.text }}</h5>
        <a href="javascript:deleteNotification({{ notification.pk }})" class="secondary-content">
            <i class="material-icons red-text">delete</i>
        </a>
    </li>
    {% endfor %}
</ul>

user/templates/user/user_detail.html
{% extends "core/containers/main_page_base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        
        <div class="col l3 hide-on-med-and-down fixed-top">
            <div class="profile-card card hoverable">
                <div class="card-content center-align">
                    {% if user.is_active and user == profile_of %}
                    <div class="row">
                        <a href='{% url 'user:profile-edit' username=profile_of.username %}'
                            class="btn btn-small left">
                            <i class="material-icons">edit</i>
                        </a>
                    </div>
                    {% endif %}
                    <div class="row">
                        <h3 class="user-username">{{ profile_of.username }}</h3>
                    </div>
                    <div class="row">
                        {{ profile_of.about_me }}
                    </div>
                    <img class="responsive-img circle" src="{{ profile_of.gravatar_url }}">
                    <div class="row section">
                        <a href="{{ profile_of.linkedin_link }}" class="black-text ml-5" href="">
                            <i class="fa fa-lg fa-linkedin"></i>
                        </a>
                        <a href="{{ profile_of.github_link }}" class="black-text ml-5" href="">
                            <i class="fa fa-lg fa-github"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col s12 hide-on-large-only">
            <div class="profile-card card hoverable">
                <div class="card-content center-align">
                    {% if user.is_active and user == profile_of %}
                    <div class="row">
                        <a href='{% url 'user:profile-edit' username=profile_of.username %}'
                            class="btn btn-small left">
                            <i class="material-icons">edit</i>
                        </a>
                    </div>
                    {% endif %}
                    <div class="row">
                        <h3 class="user-username">{{ profile_of.username }}</h3>
                    </div>
                    <div class="row">
                        {{ profile_of.about_me }}
                    </div>
                    <img class="responsive-img circle" src="{{ profile_of.gravatar_url }}">
                    <div class="row section">
                        <a class="black-text ml-5" href=""><i class="fa fa-lg fa-linkedin"></i></a>
                        <a class="black-text ml-5" href=""><i class="fa fa-lg fa-github"></i></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col l8 offset-l5 m12">
            <h4 class="title">Top Posts</h4>
            {% for obj in profile_of.get_top_posts %}
                {% include obj.child_object.short_entry_template with entry=obj %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" href="{% static "css/account.css" %}">
{% endblock css %}2

user/templates/user/user_edit.html
{% extends "core/containers/simple_form_base.html" %}

{% block form_title %}Update{% endblock form_title %}

{% block form %}{% include "core/utilities/render_form_fields.html" %}{% endblock %}

{% block actions %}
<button type="submit" class="teal-text teal-lighten-2 btn-flat btn-large">Update</button>
<a href='{% url 'user:profile' username=user.username %}' class="yellow-text btn-flat btm-large">Cancel</a>
{% endblock actions %}

user/templates/user/user_notifications.html
{% extends "core/containers/user_menu_base.html" %}

{% block main_content %}
    <div class="col l10 offset-l2">
    
        {% include "user/notifications.html" with notifications=obj %}
    
        {% if is_paginated %}
            {% include 'core/elements/pagination.html' %}
        {% endif %}
        <div class="divider hide-on-large-only"></div>
    </div>
{% endblock %}

user/templates/user/user_profile.html
<div class="profile-card card hoverable">
    {% if user and user == profile_of %}
    <a href='{% url 'user:profile-edit' username=profile_of.username %}' class="edit-profile-btn btn-floating waves-effect waves-light red right"><i class="material-icons">edit</i></a>
    {% endif %}
    <div class="card-content center-align">
        <h3 class="user-username">{{ profile_of.username }}</h3>
        <img class="responsive-img circle" src="{{ profile_of.gravatar_url }}">
        <span class="user-about-me">{{ profile_of.about_me }}</span>
    </div>

</div>