blog/urls.py
from django.conf.urls import url, include
from . import views


article_patterns = [
    url('create', views.ArticleCreateView.as_view(), name='create'),
    url(r'(?P<username>[a-zA-Z0-9_-]{1,20})/(?P<feedslug>[a-zA-Z0-9_-]{1,100})/(?P<slug>[a-zA-Z0-9_-]{1,100})/edit$',
        views.ArticleEditView.as_view(),
        name='edit'),
    url(r'(?P<username>[a-zA-Z0-9_-]{1,20})/(?P<feedslug>[a-zA-Z0-9_-]{1,100})/(?P<slug>[a-zA-Z0-9_-]{1,100})$', 
        views.ArticleDetailView.as_view(), 
        name='permalink'),
]

# question_patterns = [
#     url('create', views.CreateQuestionView.as_view(), name='create')
# ]


# url_patterns = [
#     url('create', views.CreateUrlView.as_view(), name='create')
# ]

urlpatterns = [
    # permalink for post
    # p/username/feedslug/postslug
    # url(r'p/(?P<username>[a-zA-Z0-9_-]{1,20})/(?P<feedslug>[a-zA-Z0-9_-]{1,50})/(?P<slug>[a-zA-Z0-9_-]{1,80})$', 
    #     views.ViewFeedItem.as_view(),
    #     name='permalink'),
        
    url('^article/', include(article_patterns, namespace='article')),
    # url('^question/', include(question_patterns, namespace='question')),
    # url('^url/', include(url_patterns, namespace='url'))
]

feed/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    # logged in users drafts
    url(r'drafts$', views.DraftsFeed.as_view(), name='drafts'),
    
    # list of user's feeds, also form to create feed if logged in user = username
    # f/user/feeds
    url(r'(?P<username>[a-zA-Z0-9_-]{1,20})/feeds$', 
        views.CreateFeedView.as_view(), 
        name='user-feed-list'),

    # a feed belonging to a specific user
    # f/user/myfeed
    url(r'(?P<username>[a-zA-Z0-9_-]{1,20})/(?P<feedslug>[a-zA-Z0-9_-]{1,100})$', 
        views.UserCreatedFeed.as_view(), 
        name='user-feed'),


    # view a user's feeds
    # f/user
    url(r'(?P<username>[a-zA-Z0-9_-]{1,20})$',
        views.UserFeed.as_view(),
        name='user'),

    # main feed
    url(r'^$', views.OverviewFeed.as_view(), name='overview')
]

hackshaw/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.defaults import page_not_found
from user.views import LoginView, LogoutView, RegisterView, AuthorRequestView
from core.views import RedirectView
from feed.views import OverviewFeed

urlpatterns = [
    # authentication urls
    url(r'^login$', LoginView.as_view(), name='login'),
    url(r'^register$', RegisterView.as_view(), name='register'),
    url(r'^author_request$', AuthorRequestView.as_view(), name='author-request'),
    url(r'^logout$', LogoutView.as_view(), name='logout'),

    # home page is the overview feed
    url(r'^$', OverviewFeed.as_view(), name='homepage'),

    # user profile urls
    url(r'^u/', include('user.urls', namespace='user')),

    # feed urls
    url(r'^f/', include('feed.urls', namespace='feed')),

    # article/ question/ survey/ etc.
    url(r'^', include('blog.urls', namespace='blog')),

    # admin urls
    url(r'^admin/login', RedirectView.as_view(), {'url': 'login'}),
    url(r'^admin/', admin.site.urls)

]

user/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'notifications$', views.NotificationsView.as_view(), name='notifications'),
    url(r'notifications/delete/(?P<pk>[0-9]+)$',
        views.DeleteNotificationView.as_view(), name='delete-notification'),
    url(r'(?P<username>[a-zA-Z0-9]{1,50})/profile$', views.ProfileView.as_view(), name='profile'),
    url(r'(?P<username>[a-zA-Z0-9]{1,50})/profile/edit', views.ProfileEditView.as_view(), name='profile-edit')
]

core/models.py
from django.db import models
from django.template.defaultfilters import slugify
from user.models import User



class Tag(models.Model):
    name = models.CharField(max_length=20, unique=True)
    slug = models.SlugField(max_length=30, unique=True)


    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super(Tag, self).save(*args, **kwargs)

    @staticmethod
    def get_popular(count=15):
        return Tag.objects\
                   .annotate(num_entries=models.Count('feeditem'))\
                   .order_by('-num_entries')\
                   .all()[:count]

    def __repr__(self):
        return '<Tag %r>' % self.name


class Stars(models.Model):
    user = models.ForeignKey(User, related_name='user', on_delete=models.CASCADE)

core/views.py
from django.shortcuts import render
from django.shortcuts import redirect, reverse
from django.views.generic import View


class RedirectView(View):
    def get(self, request, url):
        return redirect(reverse(url))

core/templates/core/elements/footer.html
<footer class="page-footer pt-0 transparent">
    <div class="footer-copyright">
        <div class="container black-text">
            © 2017 SemperPy
            <a class="black-text text-lighten-4 right fa fa-gitlab ml-5" href="#!"></a>
            <a class="black-text text-lighten-4 right fa fa-youtube ml-5" href="#!"></a>
            <a class="black-text text-lighten-4 right fa fa-reddit-alien ml-5" href="#!"></a>
            <a class="black-text text-lighten-4 right fa fa-linkedin ml-5" href="#!"></a>
        </div>
    </div>
</footer>

core/templates/core/elements/left_side_menu.html
{% load blog_custom_tags %}

{% if user.is_active %}
<div class="row section side-menu-user">
    <div class="col s2 right-align">
        <img class="circle" src="{% user_gravatar_url user 18 %}">
    </div>
    <div class="col s10 side-menu-item">
        <a href="{% url 'user:profile' username=user.username %}">{{ user.username }}</a>
    </div>
</div>

<div class="row">
    <div class="row side-menu-entry valign-wrapper">
        <div class="col s2 right-align">
            <i class="material-icons circle tiny">person</i>
        </div>
        <div class="col s10 side-menu-item">
            <a href="{% url 'user:profile' username=user.username %}">account</a>
        </div>
    </div>
    <div class="row side-menu-entry valign-wrapper">
        <div class="col s2 right-align">
            <i class="material-icons circle tiny">view_list</i>
        </div>
        <div class="col s10 side-menu-item">
            <a href="{% url 'feed:user' username=user.username %}">posts</a>
        </div>
    </div>
    <div class="row side-menu-entry valign-wrapper">
        <div class="col s2 right-align">
            <i class="material-icons circle tiny">star</i>
        </div>
        <div class="col s10 side-menu-item">
            <a href="{% url 'user:profile' username=user.username %}">favorites</a>
        </div>
    </div>
    <div class="row side-menu-entry valign-wrapper">
        <div class="col s2 right-align">
            <i class="material-icons circle tiny">rss_feed</i>
        </div>
        <div class="col s10 side-menu-item">
            <a href="{% url 'feed:user-feed-list' username=user.username %}">feeds</a>
        </div>
    </div>
    <div class="row side-menu-entry valign-wrapper">
        <div class="col s2 right-align">
            <i class="material-icons circle tiny">edit</i>
        </div>
        <div class="col s10 side-menu-item">
            <a href="{% url 'feed:drafts' %}">drafts</a>
        </div>
    </div>
</div>
{% endif %}

core/templates/core/elements/navbar.html
<ul id="account_dropdown" class="dropdown-content">
    {% if user.is_active %}
        <li><a href="{{ user.profile_url }}">Profile</a></li>
        {% if user.is_admin %}
        <li><a href="/admin">Admin</a></li>
        {% endif %}
        <li><a href="{% url 'logout' %}">Logout</a></li>
    {% else %}
        <li><a href="{% url 'login' %}">Login</a></li>
    {% endif %}
</ul>

<ul id="create_dropdown" class="dropdown-content">
    <li><a href="{% url 'blog:article:create' %}">Article</a></li>
    <li><a href="{% url 'blog:article:create' %}">Question</a></li>
    <li><a href="{% url 'blog:article:create' %}">Survey</a></li>
</ul>


<div class="navbar-fixed">
    <nav class="teal lighten-2">
        <div class="nav-wrapper">
            <div class="container">
                <a href="#" data-activates="mobile-demo" class="button-collapse">
                    <i class="material-icons">menu</i>
                </a>

                <ul class="hide-on-med-and-down">
                    <li><a href="{% url 'feed:overview' %}"><i class="material-icons left">home</i> Feed</a></li>
                </ul>

                <ul class="right hide-on-med-and-down">
                    {% if user.is_active %}
                    <li><a href="{% url 'user:notifications' %}">
                        Notifications
                        <i class="fa fa-bell-o fa-lg right"></i></a></li>
                    {% endif %}

                    <li><a class="dropdown-button" href="#!" data-activates="create_dropdown">Create
                        <i class="material-icons right">edit</i></a></li>

                    {% if user.is_active %}
                    <li><a class="dropdown-button" href="#!" data-activates="account_dropdown">Settings
                        <i class="material-icons right">settings</i></a></li>
                    {% else %}
                    <li><a href="{% url 'login' %}">Login
                        <i class="material-icons right">person</i></a></li>
                    {% endif %}
                </ul>
            </div>

            <ul class="side-nav" id="mobile-demo">
                <li><i class="material-icons left">home</i><a href="{% url 'feed:overview' %}">Feed</a></li>
                <li class="divider"></li>
                {% if user.is_active %}
                    <li><a href="{{ user.profile_url }}">Profile</a></li>
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

core/templates/core/elements/pagination.html
{% load navigation_tags %}

<ul class="pagination center-align">
    <li><a href="?{% replace_url_params page=1 %}"><i class="material-icons">skip_previous</i></a></li>
    {% if page_obj.has_previous %}
    <li><a href="?{% replace_url_params page=page_obj.previous_page_number %}"><i class="material-icons">chevron_left</i></a></li>
    {% else %}
    <li class="disabled"><a href=""><i class="material-icons">chevron_left</i></a></li>
    {% endif %}

    <li class="active"><a href="?{% replace_url_params page=page_obj.number %}">{{ page_obj.number }}</a></li>
    {% if page_obj.has_next %}
    <li><a href="?{% replace_url_params page=page_obj.next_page_number %}"><i class="material-icons">chevron_right</i></a></li>
    {% else %}
    <li class="disabled"><a href=""><i class="material-icons">chevron_right</i></a></li>
    {% endif %}
    <li class="waves-effect"><a href="?{% replace_url_params page=page_obj.paginator.num_pages %}"><i class="material-icons">skip_next</i></a></li>
</ul>
                

core/templates/core/elements/right_side_menu.html
{% load blog_custom_tags %}

<div class="row">
    <div class="col s12 m6 l12">
        <!-- Other feeds by the currently viewing user -->
        {% if feed_user %}
        <div class="row section side-menu-user">
            <div class="valign-wrapper">
                <div class="col s2 right-align hide-on-med-and-down">
                    <img class="responsive-img circle" src="{% user_gravatar_url feed_user 20 %}">
                </div>
                <div class="col l10 m11 offset-m1 side-menu-item">
                    <a href="{% url 'feed:user-feed-list' username=feed_user.username %}" style="color:black;">
                        Other feeds by {{ feed_user.username }}
                    </a>
                </div>
            </div>
        </div>

        {% for feed in feed_user.feeds.all|slice:"4" %}
        <div class="row side-menu-entry">
            <div class="valign-wrapper">
                <div class="col s2 right-align hide-on-med-and-down">
                    <i class="material-icons circle tiny">keyboard_arrow_right</i>
                </div>
                <div class="col l10 m11 offset-m1 side-menu-item">
                    <a href="{% url 'feed:user-feed' username=feed_user.username feedslug=feed.slug %}">
                        {{ feed.name }}
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="row side-menu-entry">
            <div class="valign-wrapper">
                <div class="col s2 right-align hide-on-med-and-down">
                    <i class="material-icons circle tiny">keyboard_arrow_right</i>
                </div>
                <div class="col l10 m11 offset-m1 side-menu-item">
                    <a href="{% url 'feed:user-feed-list' username=feed_user.username %}">
                        more
                    </a>
                </div>
            </div>
        </div>
        {% endif %}
        <!-- end other feeds  -->
    </div>

    <div class="col s12 m6 l12">
        <!-- popular tags -->
        <div class="row section side-menu-user">
            <div class="valign-wrapper">
                <div class="col s2 right-align hide-on-med-and-down">
                    <i class="material-icons circle tiny">local_offer</i>
                </div>
                <div class="col l10 m11 offset-m1 side-menu-item">
                    <span>Popular Tags</span>
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col s12">
                {% for tag in popular_tags %}
                <a href="{% url 'feed:overview' %}?tag={{ tag.slug }}" class="left chip btn-small" data-badge-caption="">{{ tag.name }}</a>
                {% endfor %}
            </div>
        </div>
        <!-- end popular tags -->
    </div>

    <div class="col s12 m6 l12">
        <!-- popular feeds -->
        <div class="row section side-menu-user">
            <div class="valign-wrapper">
                <div class="col s2 right-align hide-on-med-and-down">
                    <i class="material-icons circle tiny">trending_up</i>
                </div>
                <div class="col l10 m11 offset-m1 side-menu-item">
                    <span>Popular Feeds</span>
                </div>
            </div>
        </div>
        
        {% for feed in popular_feeds %}
        <div class="row side-menu-entry">
            <div class="valign-wrapper">
                <div class="col s2 right-align hide-on-med-and-down">
                    <i class="material-icons circle tiny">keyboard_arrow_right</i>
                </div>
                <div class="col l10 m11 offset-m1 side-menu-item ">
                    <a href="{% url 'feed:user-feed' username=feed.user.username feedslug=feed.slug %}">
                        {{ feed.name }}
                    </a><br />by {{ feed.user.username }}
                </div>
            </div>
        </div>
        {% endfor %}
        <!-- end popular feeds -->
    </div>
</div>